# Generated by Django 5.2.17 on 2026-09-05 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('template_content', models.TextField(help_text='The actual prompt text, can contain variables like {{ context }}')),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='LLMRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='openai', max_length=100)),
                ('model_name', models.CharField(default='gpt-4', max_length=100)),
                ('exact_prompt_sent', models.TextField()),
                ('raw_response', models.TextField(blank=True)),
                ('structured_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.prompttemplate')),
            ],
        ),
    ]
