# Generated by Django 5.2.17 on 2026-09-05 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('FETCHING_LOCATION', 'Fetching Location'), ('FETCHING_POI', 'Fetching POI'), ('ANALYZING_MARKET', 'Analyzing Market'), ('GENERATING_AI', 'Generating AI'), ('COMPILING_REPORT', 'Compiling Report'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('algorithm_version', models.CharField(default='1.0', max_length=50)),
                ('prompt_version', models.CharField(default='1.0', max_length=50)),
                ('input_snapshot', models.JSONField(blank=True, null=True)),
                ('external_data_snapshot', models.JSONField(blank=True, null=True)),
                ('failure_information', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_step', models.IntegerField(default=1)),
                ('lat', models.FloatField(blank=True, db_index=True, null=True)),
                ('lng', models.FloatField(blank=True, db_index=True, null=True)),
                ('expected_scale', models.CharField(blank=True, max_length=100)),
                ('available_shop', models.BooleanField(default=False)),
                ('experience_years', models.IntegerField(default=0)),
                ('number_of_workers', models.IntegerField(default=1)),
                ('target_customers', models.CharField(blank=True, max_length=200)),
                ('products', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeasibilityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.TextField(blank=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('scoring_data', models.JSONField(blank=True, help_text='Structured scoring output', null=True)),
                ('is_feasible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feasible_project_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('constrained_project_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('working_capital_estimate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cap_constrained', models.BooleanField(default=False)),
                ('constraint_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installments_data', models.JSONField(help_text='Stores full schedule array')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('current_state', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('FETCHING_LOCATION', 'Fetching Location'), ('FETCHING_POI', 'Fetching POI'), ('ANALYZING_MARKET', 'Analyzing Market'), ('GENERATING_AI', 'Generating AI'), ('COMPILING_REPORT', 'Compiling Report'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='advisory.analysisrun')),
            ],
        ),
    ]
