# Generated by Django 5.2.17 on 2026-09-05 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisory', '0001_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.block'),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advisory.businesscategory'),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.district'),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.state'),
        ),
    ]
