# Generated by Django 5.2.17 on 2026-09-05 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisory', '0002_initial'),
        ('finance', '0001_initial'),
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.village'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='advisory.businessproposal'),
        ),
        migrations.AddField(
            model_name='feasibilityreport',
            name='analysis_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='advisory.analysisrun'),
        ),
        migrations.AddField(
            model_name='financialassessment',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_assessment', to='advisory.businessproposal'),
        ),
        migrations.AddField(
            model_name='financialassessment',
            name='scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.schemedefinition'),
        ),
        migrations.AddField(
            model_name='repaymentschedule',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedule', to='advisory.financialassessment'),
        ),
    ]
