# Generated by Django 5.2.17 on 2026-09-05 08:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('retrieval_timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('verification_status', models.CharField(default='UNVERIFIED', max_length=50)),
                ('raw_data_snapshot', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitorPOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('distance_from_center_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('data_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitors', to='market.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_timestamp', models.DateTimeField(auto_now_add=True)),
                ('geographic_scope', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('category', models.CharField(help_text='e.g. demographic, price, indicator', max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('raw_value', models.JSONField()),
                ('normalized_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='market.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='MarketAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_count', models.IntegerField(default=0)),
                ('competitor_density', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('distance_to_nearest_competitor_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('market_radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_market_reach', models.IntegerField(blank=True, null=True)),
                ('service_business_gap', models.TextField(blank=True)),
                ('proximity_to_infrastructure', models.TextField(blank=True)),
                ('provenance', models.CharField(choices=[('VERIFIED_EXTERNAL_DATA', 'Verified External Data'), ('DETERMINISTIC_CALCULATION', 'Deterministic Calculation'), ('AI_GENERATED_RECOMMENDATION', 'AI Generated Recommendation'), ('ASSUMPTION_ESTIMATE', 'Assumption / Estimate')], default='DETERMINISTIC_CALCULATION', max_length=50)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.datasource')),
            ],
        ),
    ]
