# Generated by Django 5.2.17 on 2026-09-05 08:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_project_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_project_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('funding_percentage', models.DecimalField(decimal_places=2, help_text='e.g., 90.00 for 90%', max_digits=5)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate_annual', models.DecimalField(decimal_places=2, help_text='e.g., 6.50 for 6.5%', max_digits=5)),
                ('tenure_months', models.IntegerField(help_text='Total tenure in months, including moratorium')),
                ('moratorium_months', models.IntegerField(default=0)),
                ('moratorium_policy', models.CharField(choices=[('CAPITALIZE_INTEREST', 'Capitalize Interest'), ('PAY_INTEREST_ONLY', 'Pay Interest Only'), ('DEFER_INTEREST', 'Defer Interest')], default='CAPITALIZE_INTEREST', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
    ]
