# Generated by Django 5.2.17 on 2026-09-08 16:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier e.g. dairy_farming', max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(choices=[('AGRI_ALLIED', 'Agriculture & Allied'), ('MANUFACTURING', 'Rural Manufacturing & Processing'), ('SERVICE', 'Rural Services & Tech'), ('RETAIL', 'Rural Retail & Trading'), ('OTHER', 'Other Activities')], default='AGRI_ALLIED', max_length=50)),
                ('icon', models.CharField(default='Briefcase', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('unit_of_measurement', models.CharField(default='Units', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeasibilityConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profitability_weight', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('cash_flow_weight', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('dscr_weight', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('funding_weight', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('working_capital_weight', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('promoter_contribution_weight', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('risk_weight', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('dscr_strong_threshold', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4)),
                ('dscr_moderate_threshold', models.DecimalField(decimal_places=2, default=Decimal('1.20'), max_digits=4)),
                ('dscr_weak_threshold', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchemeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. PMEGP, MUDRA, AIF, PMFME', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ministry', models.CharField(blank=True, default='', max_length=255)),
                ('official_portal_url', models.URLField(blank=True, default='')),
                ('scheme_type', models.CharField(default='Capital Subsidy', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDriverTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_capacity_monthly', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=12)),
                ('default_selling_price', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('default_variable_cost_per_unit', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=12)),
                ('default_operating_days', models.IntegerField(default=26)),
                ('default_capex_breakdown', models.JSONField(default=list, help_text='Default 7-category CapEx line items')),
                ('default_fixed_costs', models.JSONField(default=list, help_text='Default monthly fixed overheads')),
                ('default_variable_costs', models.JSONField(default=list, help_text='Default variable cost drivers')),
                ('seasonal_factors', models.JSONField(default=list, help_text='12 monthly multipliers')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_template', to='finance.businessactivity')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialProjectPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Project Feasibility Plan', max_length=255)),
                ('business_stage', models.CharField(default='new', max_length=50)),
                ('location_state', models.CharField(blank=True, default='', max_length=100)),
                ('location_district', models.CharField(blank=True, default='', max_length=100)),
                ('location_block', models.CharField(blank=True, default='', max_length=100)),
                ('location_village', models.CharField(blank=True, default='', max_length=100)),
                ('rural_urban', models.CharField(default='rural', max_length=20)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('promoter_profile', models.JSONField(default=dict)),
                ('financial_inputs', models.JSONField(default=dict)),
                ('project_cost_items', models.JSONField(default=list)),
                ('calculation_results', models.JSONField(default=dict)),
                ('rule_version_used', models.CharField(blank=True, default='', max_length=50)),
                ('calculation_timestamp', models.DateTimeField(auto_now=True)),
                ('business_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.businessactivity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialPlanAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('output_snapshot', models.JSONField(default=dict)),
                ('rule_version', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='finance.financialprojectplan')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SchemeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_version', models.CharField(default='2026.01', max_length=50)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('OFFICIAL', 'Official Government Data'), ('VERIFIED', 'Verified by Financial Institution'), ('PENDING_VERIFICATION', 'Pending Verification'), ('EXPIRED', 'Expired / Superseded')], default='OFFICIAL', max_length=50)),
                ('last_verified_date', models.DateField()),
                ('source_document', models.CharField(blank=True, default='', max_length=255)),
                ('min_project_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('max_project_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('max_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('allowed_sectors', models.JSONField(default=list)),
                ('allowed_locations', models.JSONField(default=list, help_text="['rural', 'urban']")),
                ('allowed_stages', models.JSONField(default=list, help_text="['new', 'existing', 'expansion']")),
                ('min_promoter_age', models.IntegerField(default=18)),
                ('max_promoter_age', models.IntegerField(blank=True, null=True)),
                ('min_education', models.CharField(blank=True, default='', max_length=100)),
                ('promoter_contribution_matrix', models.JSONField(default=dict, help_text="e.g. {'general': 10.0, 'special': 5.0}")),
                ('subsidy_rate_matrix', models.JSONField(default=dict, help_text="e.g. {'general_urban': 15.0, 'general_rural': 25.0, 'special_urban': 25.0, 'special_rural': 35.0}")),
                ('max_subsidy_cap', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('subsidy_timing', models.CharField(choices=[('BACK_ENDED', 'Back-Ended Capital Subsidy (TDR)'), ('UPFRONT', 'Upfront Capital Subsidy'), ('CAPITAL_SUBSIDY', 'Credit-Linked Capital Subsidy'), ('INTEREST_SUBVENTION', 'Interest Rate Subvention'), ('REIMBURSEMENT', 'Reimbursement')], default='BACK_ENDED', max_length=50)),
                ('interest_rate_annual', models.DecimalField(decimal_places=2, default=Decimal('8.50'), max_digits=5)),
                ('interest_subvention_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tenure_months', models.IntegerField(default=84)),
                ('moratorium_months', models.IntegerField(default=6)),
                ('moratorium_policy', models.CharField(choices=[('CAPITALIZE_INTEREST', 'Capitalize Interest'), ('PAY_INTEREST_ONLY', 'Pay Interest Only'), ('DEFER_INTEREST', 'Defer Interest')], default='PAY_INTEREST_ONLY', max_length=50)),
                ('collateral_support', models.CharField(blank=True, default='', max_length=255)),
                ('state_top_ups', models.JSONField(default=dict, help_text='State-specific top-up subsidies')),
                ('required_documents', models.JSONField(default=list)),
                ('special_conditions', models.TextField(blank=True, default='')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='finance.schememaster')),
            ],
            options={
                'ordering': ['-effective_from', '-rule_version'],
                'unique_together': {('scheme', 'rule_version')},
            },
        ),
        migrations.AddField(
            model_name='financialprojectplan',
            name='matched_scheme_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.schemerule'),
        ),
    ]
