# Generated by Django 5.2.17 on 2026-09-08 16:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovtScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('official_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('short_name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('level', models.CharField(choices=[('CENTRAL', 'Central Government'), ('STATE', 'State Government'), ('LOCAL', 'District / Local Agency')], default='CENTRAL', max_length=20)),
                ('state', models.CharField(blank=True, db_index=True, default='', help_text='e.g. Gujarat (empty for Central schemes)', max_length=100)),
                ('districts', models.JSONField(blank=True, default=list, help_text='List of district names if district-specific')),
                ('ministry', models.CharField(db_index=True, max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('nodal_agency', models.CharField(blank=True, default='', max_length=255)),
                ('sectors', models.JSONField(default=list, help_text="e.g. ['Dairy & Livestock', 'Agriculture & Allied']")),
                ('description', models.TextField()),
                ('short_description', models.TextField(blank=True, default='')),
                ('target_audience', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active & Accepting Applications'), ('EXPIRED', 'Expired / Superseded'), ('PENDING_VERIFICATION', 'Pending Official Verification')], db_index=True, default='ACTIVE', max_length=30)),
                ('official_portal_url', models.URLField(blank=True, default='')),
                ('source_name', models.CharField(default='Official Government Scheme Portal', max_length=255)),
                ('source_url', models.URLField(blank=True, default='')),
                ('source_document', models.CharField(blank=True, default='', max_length=255)),
                ('source_document_date', models.DateField(blank=True, null=True)),
                ('last_verified_date', models.DateField(db_index=True)),
                ('verification_status', models.CharField(choices=[('OFFICIAL', 'Official Government Data'), ('VERIFIED', 'Verified by Financial Institution'), ('PENDING_VERIFICATION', 'Pending Verification'), ('EXPIRED', 'Expired / Superseded')], db_index=True, default='OFFICIAL', max_length=30)),
                ('scheme_version', models.CharField(default='2026.01', max_length=50)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('priority_score', models.IntegerField(default=100)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchemeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(default='Landmark', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Scheme Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchemeApplicationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('portal_url', models.URLField(blank=True, default='')),
                ('expected_time_days', models.IntegerField(default=15)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_steps', to='schemes.govtscheme')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='SchemeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('old_values', models.JSONField(default=dict)),
                ('new_values', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='schemes.govtscheme')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SchemeBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(choices=[('CAPITAL_SUBSIDY', 'Capital Subsidy'), ('INTEREST_SUBVENTION', 'Interest Subvention'), ('CREDIT_GUARANTEE', 'Credit Guarantee Cover'), ('LOAN_SUPPORT', 'Term Loan / Working Capital'), ('GRANT', 'Direct Grant Support'), ('WORKING_CAPITAL', 'Working Capital Assistance'), ('COLLATERAL_FREE', 'Collateral-Free Loan'), ('TRAINING_INFRA', 'Training & Skill Development'), ('INSURANCE', 'Risk & Insurance Coverage')], max_length=50)),
                ('calculation_type', models.CharField(choices=[('PERCENTAGE', 'Percentage of Eligible Cost'), ('FIXED', 'Fixed Lump-Sum Amount'), ('TIERED_PERCENTAGE', 'Tiered Percentage'), ('INTEREST_SPREAD', 'Annual Interest Rate Discount')], default='PERCENTAGE', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('eligible_base_description', models.CharField(blank=True, default='', max_length=255)),
                ('conditions', models.TextField(blank=True, default='')),
                ('is_primary', models.BooleanField(default=False)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='schemes.govtscheme')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.AddField(
            model_name='govtscheme',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemes', to='schemes.schemecategory'),
        ),
        migrations.CreateModel(
            name='SchemeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('requirement_level', models.CharField(choices=[('REQUIRED', 'Mandatory Document'), ('CONDITIONAL', 'Conditional on Category/Project'), ('OPTIONAL', 'Optional / Supporting')], default='REQUIRED', max_length=30)),
                ('issuing_authority', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='schemes.govtscheme')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SchemeEligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(db_index=True, help_text='e.g. state, rural_urban, age, gender, project_cost, sector', max_length=100)),
                ('operator', models.CharField(default='=', help_text='=, !=, >, >=, <, <=, IN, NOT_IN, BETWEEN, CONTAINS', max_length=20)),
                ('expected_value', models.JSONField(help_text='Target value or array of values')),
                ('condition_group', models.CharField(default='DEFAULT', max_length=50)),
                ('priority', models.IntegerField(default=1)),
                ('rule_description', models.TextField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='schemes.govtscheme')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SchemeFinancialRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_project_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('max_project_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('max_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('min_promoter_margin_pct', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('promoter_margin_special_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('subsidy_rate_general_urban', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('subsidy_rate_general_rural', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('subsidy_rate_special_urban', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('subsidy_rate_special_rural', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('max_subsidy_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('subsidy_timing', models.CharField(choices=[('BACK_ENDED', 'Back-Ended Capital Subsidy (TDR)'), ('UPFRONT', 'Upfront Capital Subsidy')], default='BACK_ENDED', max_length=50)),
                ('interest_rate_min', models.DecimalField(decimal_places=2, default=Decimal('8.50'), max_digits=5)),
                ('interest_rate_max', models.DecimalField(decimal_places=2, default=Decimal('11.50'), max_digits=5)),
                ('interest_subvention_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('subvention_tenure_years', models.IntegerField(default=0)),
                ('tenure_months_max', models.IntegerField(default=84)),
                ('moratorium_months_max', models.IntegerField(default=6)),
                ('collateral_type', models.CharField(default='Collateral-Free via Credit Guarantee', max_length=255)),
                ('scheme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_rule', to='schemes.govtscheme')),
            ],
        ),
        migrations.CreateModel(
            name='SavedScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('notify_updates', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='schemes.govtscheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_schemes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'scheme')},
            },
        ),
    ]
