import datetime
from decimal import Decimal
from django.core.management.base import BaseCommand
from schemes.models import (
    SchemeCategory, 
    GovtScheme, 
    SchemeBenefit, 
    SchemeEligibilityRule, 
    SchemeFinancialRule, 
    SchemeDocument, 
    SchemeApplicationStep,
    GovernmentLevel,
    SchemeStatus,
    VerificationStatus,
    BenefitType,
    CalculationType,
    RequirementLevel,
    SubsidyTiming
)


class Command(BaseCommand):
    help = 'Seeds verified Central and State Government Schemes, categories, rules, and documents.'

    def handle(self, *args, **options):
        self.stdout.write(self.style.NOTICE("Seeding dynamic government schemes repository..."))

        # -------------------------------------------------------------
        # 1. Scheme Categories
        # -------------------------------------------------------------
        categories_data = [
            {'name': 'Dairy & Livestock', 'slug': 'dairy-livestock', 'icon': 'Milk', 'order': 1, 'desc': 'Schemes supporting cattle, milk chilling hubs, breeding and animal husbandry.'},
            {'name': 'Agriculture & Food Processing', 'slug': 'agriculture-food', 'icon': 'Sprout', 'order': 2, 'desc': 'Post-harvest processing, cold storage, oil mills, flour units and organic food.'},
            {'name': 'MSME & Manufacturing', 'slug': 'msme-manufacturing', 'icon': 'Factory', 'order': 3, 'desc': 'Credit-linked subsidies, working capital and collateral-free term loans for rural enterprises.'},
            {'name': 'Women & SHGs', 'slug': 'women-shgs', 'icon': 'Users', 'order': 4, 'desc': 'Priority funding, 0% interest and high capital subsidies for women entrepreneurs.'},
            {'name': 'Renewable & Green Energy', 'slug': 'renewable-green', 'icon': 'Sun', 'order': 5, 'desc': 'Solar pumps, rooftop setups, biogas, and green infrastructure initiatives.'},
            {'name': 'Handicraft & Artisans', 'slug': 'handicraft-artisan', 'icon': 'Palette', 'order': 6, 'desc': 'Rural handloom, traditional craft workshops, toolkits and marketing support.'},
            {'name': 'Rural Services & Logistics', 'slug': 'rural-services', 'icon': 'Truck', 'order': 7, 'desc': 'Agri-drones, custom hiring centres, transport vehicles, repair workshops and rural retail.'},
            {'name': 'Fisheries & Aquaculture', 'slug': 'fisheries', 'icon': 'Fish', 'order': 8, 'desc': 'Fish farming ponds, biofloc, cold chains and marine value-addition.'},
            {'name': 'Farm Infrastructure & Storage', 'slug': 'infrastructure', 'icon': 'Warehouse', 'order': 9, 'desc': 'Warehouses, cold rooms, grading units, pack houses and modern silos.'},
        ]

        category_objs = {}
        for cat in categories_data:
            obj, _ = SchemeCategory.objects.update_or_create(
                slug=cat['slug'],
                defaults={
                    'name': cat['name'],
                    'icon': cat['icon'],
                    'description': cat['desc'],
                    'sort_order': cat['order']
                }
            )
            category_objs[cat['slug']] = obj

        self.stdout.write(self.style.SUCCESS(f"Seeded {len(category_objs)} categories."))

        # -------------------------------------------------------------
        # 2. Central & State Schemes Master Data
        # -------------------------------------------------------------
        schemes_data = [
            # 1. PMEGP
            {
                'official_id': 'PMEGP',
                'name': "Prime Minister's Employment Generation Programme",
                'short_name': 'PMEGP',
                'slug': 'pmegp',
                'level': GovernmentLevel.CENTRAL,
                'state': '',
                'ministry': 'Ministry of Micro, Small and Medium Enterprises (MSME)',
                'department': 'Department of MSME',
                'nodal_agency': 'Khadi and Village Industries Commission (KVIC) & DIC',
                'category': category_objs['msme-manufacturing'],
                'sectors': ['Rural Manufacturing', 'Food Processing', 'Rural Services', 'Artisanal & Crafts'],
                'description': 'Flagship credit-linked capital subsidy programme designed to foster sustainable self-employment by assisting entrepreneurs to set up micro-enterprises in non-farm manufacturing and service sectors.',
                'short_description': 'Up to 35% capital subsidy (up to ₹17.5 Lakh) for non-farm rural manufacturing and service micro-enterprises.',
                'target_audience': 'Rural Individuals, SHGs, Co-operatives, Artisans (Age 18+, min 8th pass for >₹10L)',
                'official_portal_url': 'https://www.kviconline.gov.in/pmegpeportal/',
                'source_name': 'KVIC / Ministry of MSME Operational Guidelines',
                'source_document': 'MoMSME Circular No. PMEGP/Policy/2022-26',
                'source_document_date': datetime.date(2022, 6, 1),
                'last_verified_date': datetime.date(2026, 1, 15),
                'verification_status': VerificationStatus.OFFICIAL,
                'scheme_version': '2026.01',
                'priority_score': 100,
                'keywords': ['subsidy', 'manufacturing', 'service', 'kvic', 'pmegp', 'loan', 'capital subsidy'],
                'fin': {
                    'min_cost': Decimal('50000.00'),
                    'max_cost': Decimal('5000000.00'),
                    'max_loan': Decimal('4750000.00'),
                    'margin_gen': Decimal('10.00'),
                    'margin_spec': Decimal('5.00'),
                    'sub_gen_urb': Decimal('15.00'),
                    'sub_gen_rur': Decimal('25.00'),
                    'sub_spec_urb': Decimal('25.00'),
                    'sub_spec_rur': Decimal('35.00'),
                    'max_sub': Decimal('1750000.00'),
                    'timing': SubsidyTiming.BACK_ENDED,
                    'rate_min': Decimal('8.50'),
                    'rate_max': Decimal('10.50'),
                    'subvention': Decimal('0.00'),
                    'subvention_years': 0,
                    'tenure': 84,
                    'moratorium': 6,
                    'collateral': 'Collateral-free up to ₹10 Lakh (CGTMSE covered)',
                },
                'benefits': [
                    {'title': 'Capital Subsidy up to 35%', 'type': BenefitType.CAPITAL_SUBSIDY, 'calc': CalculationType.PERCENTAGE, 'pct': Decimal('35.00'), 'max': Decimal('1750000.00'), 'primary': True, 'desc': '25% in urban, 35% in rural for special categories (Women, SC/ST/OBC/Minority/Divyang).'},
                    {'title': 'Low Promoter Margin (5% to 10%)', 'type': BenefitType.LOAN_SUPPORT, 'calc': CalculationType.PERCENTAGE, 'pct': Decimal('95.00'), 'desc': 'Banks finance 90% to 95% of total project outlay.'},
                    {'title': 'Collateral-Free Credit', 'type': BenefitType.COLLATERAL_FREE, 'calc': CalculationType.FIXED, 'fixed': Decimal('1000000.00'), 'desc': 'No third party guarantee or collateral security required up to ₹10 Lakh.'},
                    {'title': 'Second Loan for Expansion', 'type': BenefitType.LOAN_SUPPORT, 'calc': CalculationType.FIXED, 'max': Decimal('10000000.00'), 'desc': 'Up to ₹1 Crore for upgradation of successfully functioning existing PMEGP units.'},
                ],
                'rules': [
                    {'field': 'age', 'op': '>=', 'val': 18, 'desc': 'Applicant must be at least 18 years of age.'},
                    {'field': 'business_stage', 'op': 'IN', 'val': ['new'], 'desc': 'Applicable only to new venture units. Existing units not eligible.'},
                    {'field': 'rural_urban', 'op': 'IN', 'val': ['rural', 'urban'], 'desc': 'Both rural and urban areas are eligible (higher subsidy in rural areas).'},
                ],
                'docs': [
                    {'name': 'Aadhaar Card & PAN Card', 'req': RequirementLevel.REQUIRED, 'desc': 'Proof of identity and PAN for tax and credit verification.'},
                    {'name': 'Detailed Project Report (DPR)', 'req': RequirementLevel.REQUIRED, 'desc': 'Comprehensive technical and financial project report including cash flow projections.'},
                    {'name': 'Rural Area Certificate', 'req': RequirementLevel.REQUIRED, 'desc': 'Issued by Gram Panchayat / Taluka Development Officer to claim 35% rural subsidy.'},
                    {'name': 'Educational Qualification Proof (8th Pass+)', 'req': RequirementLevel.CONDITIONAL, 'desc': 'Mandatory for manufacturing projects >₹10 Lakh and service projects >₹5 Lakh.'},
                    {'name': 'Caste / Special Category Certificate', 'req': RequirementLevel.CONDITIONAL, 'desc': 'Issued by competent revenue authority for SC/ST/OBC/Divyang benefits.'},
                    {'name': 'Bank Passbook / Cancelled Cheque', 'req': RequirementLevel.REQUIRED, 'desc': 'Passbook with last 6 months transactions.'},
                ],
                'steps': [
                    {'step': 1, 'title': 'Online Portal Registration', 'desc': 'Submit online application with personal, location, and project cost details on KVIC e-portal.', 'portal': 'https://www.kviconline.gov.in/pmegpeportal/'},
                    {'step': 2, 'title': 'DPR Upload & Agency Selection', 'desc': 'Upload bank-ready DPR, KYC documents, and select preferred financing bank branch and implementing agency (KVIC/KVIB/DIC).'},
                    {'step': 3, 'title': 'Agency Verification & Bank Forwarding', 'desc': 'Nodal agency scrutinizes application within 15-21 days and forwards approved file to the financing bank.'},
                    {'step': 4, 'title': 'Bank Credit Appraisal & Sanction', 'desc': 'Bank inspects project viability, conducts CIBIL check, and issues in-principle sanction letter.'},
                    {'step': 5, 'title': 'EDP Entrepreneurship Training', 'desc': 'Complete mandatory 5-10 day online/offline Entrepreneurship Development Programme (EDP) training.'},
                    {'step': 6, 'title': 'Disbursement & TDR Subsidy Lock-in', 'desc': 'Bank disburses first loan installment; KVIC credits subsidy into a 3-year locked Term Deposit Receipt (TDR).'},
                ]
            },

            # 2. PM MUDRA
            {
                'official_id': 'PM_MUDRA',
                'name': 'Pradhan Mantri MUDRA Yojana',
                'short_name': 'PM MUDRA',
                'slug': 'pm-mudra',
                'level': GovernmentLevel.CENTRAL,
                'state': '',
                'ministry': 'Ministry of Finance / Department of Financial Services',
                'department': 'Department of Financial Services',
                'nodal_agency': 'MUDRA Ltd / Commercial Banks, RRBs & SFBs',
                'category': category_objs['msme-manufacturing'],
                'sectors': ['Rural Retail & Trading', 'Small Manufacturing', 'Rural Services', 'Allied Agriculture'],
                'description': 'National credit guarantee initiative providing institutional collateral-free loans up to ₹20 Lakh across Shishu, Kishore, Tarun, and Tarun Plus tiers for non-corporate, non-farm small/micro enterprises.',
                'short_description': 'Collateral-free institutional bank loans up to ₹20 Lakh under Shishu, Kishore, and Tarun categories.',
                'target_audience': 'Shopkeepers, fruit/veg vendors, small manufacturers, rural repair workshops, transport operators',
                'official_portal_url': 'https://www.mudra.org.in/',
                'source_name': 'MUDRA / Department of Financial Services Portal',
                'source_document': 'DFS Guidelines on MUDRA Yojana 2024 Revision',
                'source_document_date': datetime.date(2024, 7, 23),
                'last_verified_date': datetime.date(2026, 1, 10),
                'verification_status': VerificationStatus.OFFICIAL,
                'scheme_version': '2026.01',
                'priority_score': 95,
                'keywords': ['mudra', 'loan', 'collateral-free', 'shishu', 'kishore', 'tarun', 'working capital'],
                'fin': {
                    'min_cost': Decimal('10000.00'),
                    'max_cost': Decimal('2000000.00'),
                    'max_loan': Decimal('2000000.00'),
                    'margin_gen': Decimal('10.00'),
                    'margin_spec': Decimal('5.00'),
                    'sub_gen_urb': Decimal('0.00'),
                    'sub_gen_rur': Decimal('0.00'),
                    'sub_spec_urb': Decimal('0.00'),
                    'sub_spec_rur': Decimal('0.00'),
                    'max_sub': Decimal('0.00'),
                    'timing': SubsidyTiming.UPFRONT,
                    'rate_min': Decimal('8.50'),
                    'rate_max': Decimal('11.50'),
                    'subvention': Decimal('0.00'),
                    'subvention_years': 0,
                    'tenure': 60,
                    'moratorium': 6,
                    'collateral': '100% Collateral-Free via CGFMU Guarantee Cover',
                },
                'benefits': [
                    {'title': 'Collateral-Free Credit Guarantee', 'type': BenefitType.COLLATERAL_FREE, 'calc': CalculationType.PERCENTAGE, 'pct': Decimal('100.00'), 'primary': True, 'desc': 'Guaranteed by Credit Guarantee Fund for Micro Units (CGFMU). No property or third party pledge.'},
                    {'title': 'Multi-Tiered Borrowing Limits', 'type': BenefitType.LOAN_SUPPORT, 'calc': CalculationType.FIXED, 'max': Decimal('2000000.00'), 'desc': 'Shishu (up to ₹50K), Kishore (₹50K-₹5L), Tarun (₹5L-₹10L), and Tarun Plus (up to ₹20L).'},
                    {'title': 'Mudra RuPay Debit Card', 'type': BenefitType.WORKING_CAPITAL, 'calc': CalculationType.PERCENTAGE, 'desc': 'Cash credit limit accessible through pre-loaded debit card for dynamic working capital management.'},
                ],
                'rules': [
                    {'field': 'age', 'op': '>=', 'val': 18, 'desc': 'Minimum age of promoter must be 18 years.'},
                    {'field': 'project_cost', 'op': '<=', 'val': 2000000, 'desc': 'Total borrowing requirement must not exceed ₹20 Lakh.'},
                ],
                'docs': [
                    {'name': 'Identity & Address Proof (Aadhaar / Voter ID)', 'req': RequirementLevel.REQUIRED, 'desc': 'Valid KYC proofs of identity and enterprise address.'},
                    {'name': 'Udyam Registration Certificate', 'req': RequirementLevel.REQUIRED, 'desc': 'Free MSME registration certificate from udyamregistration.gov.in.'},
                    {'name': 'Bank Account Statement (6 Months)', 'req': RequirementLevel.REQUIRED, 'desc': 'Recent bank transaction history.'},
                    {'name': 'Quotation / Proforma Invoices for Machinery', 'req': RequirementLevel.REQUIRED, 'desc': 'Formal quotation for tools, assets, and equipment to be purchased.'},
                ],
                'steps': [
                    {'step': 1, 'title': 'Business Plan & Machinery Quotations', 'desc': 'Prepare simple outline of enterprise activities, projected revenue, and collect supplier quotations.'},
                    {'step': 2, 'title': 'Apply on JanSamarth Portal', 'desc': 'Submit digital application on www.jansamarth.in or directly at nearby Public Sector Bank / RRB branch.'},
                    {'step': 3, 'title': 'Bank Credit Review & CIBIL Check', 'desc': 'Bank branch evaluates project repayment capacity and verifies credit bureau track record.'},
                    {'step': 4, 'title': 'Sanction & Loan Account Disbursement', 'desc': 'Bank issues sanction letter under chosen tier; term loan disbursed to supplier and working capital card issued.'},
                ]
            },

            # 3. PMFME
            {
                'official_id': 'PMFME',
                'name': 'PM Formalisation of Micro food processing Enterprises Scheme',
                'short_name': 'PMFME',
                'slug': 'pmfme',
                'level': GovernmentLevel.CENTRAL,
                'state': '',
                'ministry': 'Ministry of Food Processing Industries (MoFPI)',
                'department': 'Department of Food Processing',
                'nodal_agency': 'State Nodal Agencies (SNA) & MoFPI',
                'category': category_objs['agriculture-food'],
                'sectors': ['Food Processing', 'Agro-Allied', 'Dairy Processing', 'Organic Produce'],
                'description': 'Centrally sponsored credit-linked subsidy scheme under Aatmanirbhar Bharat Abhiyan to upgrade existing and establish new micro-food processing units with a special focus on One District One Product (ODOP).',
                'short_description': '35% credit-linked capital subsidy up to ₹10 Lakh for micro food processing enterprises and ODOP units.',
                'target_audience': 'Food Processing Entrepreneurs, FPOs, SHGs, Producer Co-operatives',
                'official_portal_url': 'https://pmfme.mofpi.gov.in/',
                'source_name': 'Ministry of Food Processing Industries (MoFPI) Portal',
                'source_document': 'MoFPI PMFME Scheme Guidelines 2021-26',
                'source_document_date': datetime.date(2021, 4, 15),
                'last_verified_date': datetime.date(2026, 1, 12),
                'verification_status': VerificationStatus.OFFICIAL,
                'scheme_version': '2026.01',
                'priority_score': 92,
                'keywords': ['pmfme', 'food processing', 'odop', 'subsidy', 'flour mill', 'oil mill', 'spices'],
                'fin': {
                    'min_cost': Decimal('100000.00'),
                    'max_cost': Decimal('3000000.00'),
                    'max_loan': Decimal('2700000.00'),
                    'margin_gen': Decimal('10.00'),
                    'margin_spec': Decimal('10.00'),
                    'sub_gen_urb': Decimal('35.00'),
                    'sub_gen_rur': Decimal('35.00'),
                    'sub_spec_urb': Decimal('35.00'),
                    'sub_spec_rur': Decimal('35.00'),
                    'max_sub': Decimal('1000000.00'),
                    'timing': SubsidyTiming.BACK_ENDED,
                    'rate_min': Decimal('8.50'),
                    'rate_max': Decimal('10.50'),
                    'subvention': Decimal('0.00'),
                    'subvention_years': 0,
                    'tenure': 84,
                    'moratorium': 6,
                    'collateral': 'CGTMSE eligible collateral-free financing',
                },
                'benefits': [
                    {'title': '35% Credit-Linked Capital Subsidy', 'type': BenefitType.CAPITAL_SUBSIDY, 'calc': CalculationType.PERCENTAGE, 'pct': Decimal('35.00'), 'max': Decimal('1000000.00'), 'primary': True, 'desc': '35% subsidy on eligible project cost, capped at ₹10 Lakh per enterprise.'},
                    {'title': 'Seed Capital for SHGs', 'type': BenefitType.GRANT, 'calc': CalculationType.FIXED, 'fixed': Decimal('40000.00'), 'desc': '₹40,000 per member seed capital for working capital and small tool purchases.'},
                    {'title': 'Marketing & Branding Grant', 'type': BenefitType.GRANT, 'calc': CalculationType.PERCENTAGE, 'pct': Decimal('50.00'), 'desc': 'Up to 50% grant support for ODOP product branding and packaging.'},
                ],
                'rules': [
                    {'field': 'age', 'op': '>=', 'val': 18, 'desc': 'Applicant must be at least 18 years old.'},
                    {'field': 'sector', 'op': 'CONTAINS', 'val': 'food', 'desc': 'Enterprise must engage in food processing or agro-product value addition.'},
                ],
                'docs': [
                    {'name': 'Aadhaar & PAN Card', 'req': RequirementLevel.REQUIRED, 'desc': 'Primary identity documents.'},
                    {'name': 'FSSAI License / Registration (or Undertaking)', 'req': RequirementLevel.REQUIRED, 'desc': 'Food safety registration or undertaking to obtain upon sanction.'},
                    {'name': 'Detailed Project Report (DPR) for Food Unit', 'req': RequirementLevel.REQUIRED, 'desc': 'Itemized plant and machinery setup costs and hygiene compliance.'},
                    {'name': 'Proof of Land / Shed Possession', 'req': RequirementLevel.REQUIRED, 'desc': 'Electricity bill, rental agreement, or land record.'},
                ],
                'steps': [
                    {'step': 1, 'title': 'Portal Registration', 'desc': 'Sign up on the PMFME portal (pmfme.mofpi.gov.in) with applicant and location profile.'},
                    {'step': 2, 'title': 'District Resource Person (DRP) Assistance', 'desc': 'Get free technical assistance from assigned DRP to formulate DPR and upload documents.'},
                    {'step': 3, 'title': 'District Level Committee (DLC) Review', 'desc': 'DLC examines eligibility against One District One Product (ODOP) priority and endorses file.'},
                    {'step': 4, 'title': 'Bank Sanction & Subsidy Disbursal', 'desc': 'Lending bank sanctions credit line and claims 35% back-ended capital subsidy from MoFPI.'},
                ]
            },

            # 4. AIF
            {
                'official_id': 'AIF',
                'name': 'Agriculture Infrastructure Fund',
                'short_name': 'AIF',
                'slug': 'aif',
                'level': GovernmentLevel.CENTRAL,
                'state': '',
                'ministry': 'Ministry of Agriculture & Farmers Welfare',
                'department': 'Department of Agriculture & Farmers Welfare',
                'nodal_agency': 'MoAFW & NABARD',
                'category': category_objs['infrastructure'],
                'sectors': ['Warehousing & Silos', 'Cold Chains', 'Sorting & Grading Units', 'Post-Harvest Infra'],
                'description': 'Central medium-long term debt financing facility providing 3% annual interest subvention and CGTMSE credit guarantee for post-harvest management infrastructure and community farming assets.',
                'short_description': '3% annual interest subvention for 7 years + CGTMSE credit guarantee for post-harvest infrastructure loans up to ₹2 Crore.',
                'target_audience': 'Agri-Entrepreneurs, Primary Agricultural Credit Societies (PACS), FPOs, SHGs, Startups',
                'official_portal_url': 'https://agriinfra.dac.gov.in/',
                'source_name': 'Ministry of Agriculture & Farmers Welfare AIF Portal',
                'source_document': 'Operational Guidelines for AIF (Revised 2024)',
                'source_document_date': datetime.date(2024, 2, 1),
                'last_verified_date': datetime.date(2026, 1, 14),
                'verification_status': VerificationStatus.OFFICIAL,
                'scheme_version': '2026.01',
                'priority_score': 90,
                'keywords': ['aif', 'cold storage', 'warehouse', 'interest subvention', 'nabard', 'silo', 'pack house'],
                'fin': {
                    'min_cost': Decimal('500000.00'),
                    'max_cost': Decimal('20000000.00'),
                    'max_loan': Decimal('20000000.00'),
                    'margin_gen': Decimal('10.00'),
                    'margin_spec': Decimal('10.00'),
                    'sub_gen_urb': Decimal('0.00'),
                    'sub_gen_rur': Decimal('0.00'),
                    'sub_spec_urb': Decimal('0.00'),
                    'sub_spec_rur': Decimal('0.00'),
                    'max_sub': Decimal('0.00'),
                    'timing': SubsidyTiming.BACK_ENDED,
                    'rate_min': Decimal('6.00'),
                    'rate_max': Decimal('8.00'),
                    'subvention': Decimal('3.00'),
                    'subvention_years': 7,
                    'tenure': 84,
                    'moratorium': 12,
                    'collateral': 'CGTMSE fee paid by Govt for loans up to ₹2 Crore',
                },
                'benefits': [
                    {'title': '3% Interest Subvention for 7 Years', 'type': BenefitType.INTEREST_SUBVENTION, 'calc': CalculationType.INTEREST_SPREAD, 'pct': Decimal('3.00'), 'primary': True, 'desc': '3% annual interest rebate credited directly to loan account for loans up to ₹2 Crore.'},
                    {'title': 'Govt Paid CGTMSE Guarantee Cover', 'type': BenefitType.CREDIT_GUARANTEE, 'calc': CalculationType.PERCENTAGE, 'pct': Decimal('100.00'), 'desc': 'Credit guarantee coverage fee under CGTMSE borne entirely by Central Govt.'},
                    {'title': 'Up to 2 Years Repayment Moratorium', 'type': BenefitType.LOAN_SUPPORT, 'calc': CalculationType.FIXED, 'desc': 'Moratorium for repayment may vary between 6 months to 24 months.'},
                ],
                'rules': [
                    {'field': 'age', 'op': '>=', 'val': 18, 'desc': 'Applicant must be at least 18 years of age.'},
                    {'field': 'project_cost', 'op': '<=', 'val': 20000000, 'desc': 'Interest subvention benefit applies to loans up to ₹2 Crore (projects can be larger).'},
                ],
                'docs': [
                    {'name': 'DPR for Post-Harvest Asset Setup', 'req': RequirementLevel.REQUIRED, 'desc': 'Technical drawings, capacity justification, civil & equipment quotes.'},
                    {'name': 'Land Ownership / Long Lease Document (15+ Years)', 'req': RequirementLevel.REQUIRED, 'desc': 'Clear title deed or registered lease agreement for project site.'},
                    {'name': 'KYC of Directors / Partners / Proprietor', 'req': RequirementLevel.REQUIRED, 'desc': 'Aadhaar, PAN, and address verifications.'},
                ],
                'steps': [
                    {'step': 1, 'title': 'Portal Registration & Application', 'desc': 'Register on agriinfra.dac.gov.in with enterprise details and upload DPR.'},
                    {'step': 2, 'title': 'Ministry PMU Verification', 'desc': 'Project Management Unit verifies technical feasibility within 7 working days.'},
                    {'step': 3, 'title': 'Bank Appraisal & Sanction', 'desc': 'Selected commercial bank/RRB branch processes loan application and approves sanction.'},
                    {'step': 4, 'title': 'Subvention Tagging & Release', 'desc': 'Govt of India automatically credits 3% annual interest subvention directly to the borrower loan account.'},
                ]
            },

            # 5. AHIDF
            {
                'official_id': 'AHIDF',
                'name': 'Animal Husbandry Infrastructure Development Fund',
                'short_name': 'AHIDF',
                'slug': 'ahidf',
                'level': GovernmentLevel.CENTRAL,
                'state': '',
                'ministry': 'Ministry of Fisheries, Animal Husbandry and Dairying',
                'department': 'Department of Animal Husbandry & Dairying',
                'nodal_agency': 'DAHD & SIDBI',
                'category': category_objs['dairy-livestock'],
                'sectors': ['Dairy Processing', 'Cattle Feed Manufacturing', 'Breed Multiplication', 'Meat Processing'],
                'description': 'A ₹15,000 Crore stimulus fund incentivizing private dairy processing units, cattle feed factories, value-added milk products, and animal waste management facilities.',
                'short_description': '3% interest subvention for 8 years and up to 25% credit guarantee for dairy processing & cattle feed plants.',
                'target_audience': 'Dairy Entrepreneurs, Private Companies, FPOs, Section 8 Entities, Dairy Co-operatives',
                'official_portal_url': 'https://ahidf.udyamimitra.in/',
                'source_name': 'Department of Animal Husbandry & Dairying (DAHD)',
                'source_document': 'DAHD AHIDF Revised Operational Guidelines',
                'source_document_date': datetime.date(2023, 10, 1),
                'last_verified_date': datetime.date(2026, 1, 10),
                'verification_status': VerificationStatus.OFFICIAL,
                'scheme_version': '2026.01',
                'priority_score': 88,
                'keywords': ['ahidf', 'dairy', 'milk processing', 'cattle feed', 'cheese', 'chilling unit', 'animal husbandry'],
                'fin': {
                    'min_cost': Decimal('1000000.00'),
                    'max_cost': Decimal('50000000.00'),
                    'max_loan': Decimal('45000000.00'),
                    'margin_gen': Decimal('10.00'),
                    'margin_spec': Decimal('10.00'),
                    'sub_gen_urb': Decimal('0.00'),
                    'sub_gen_rur': Decimal('0.00'),
                    'sub_spec_urb': Decimal('0.00'),
                    'sub_spec_rur': Decimal('0.00'),
                    'max_sub': Decimal('0.00'),
                    'timing': SubsidyTiming.BACK_ENDED,
                    'rate_min': Decimal('5.50'),
                    'rate_max': Decimal('7.50'),
                    'subvention': Decimal('3.00'),
                    'subvention_years': 8,
                    'tenure': 96,
                    'moratorium': 24,
                    'collateral': 'Credit guarantee cover up to 25% through NABARD fund',
                },
                'benefits': [
                    {'title': '3% Interest Subvention for 8 Years', 'type': BenefitType.INTEREST_SUBVENTION, 'calc': CalculationType.INTEREST_SPREAD, 'pct': Decimal('3.00'), 'primary': True, 'desc': 'Subvention directly reduces borrowing interest rate for up to 8 years.'},
                    {'title': 'Financing Up to 90% of Project Cost', 'type': BenefitType.LOAN_SUPPORT, 'calc': CalculationType.PERCENTAGE, 'pct': Decimal('90.00'), 'desc': 'Only 10% promoter contribution needed for MSME enterprises.'},
                    {'title': '2-Year Principal Repayment Moratorium', 'type': BenefitType.LOAN_SUPPORT, 'calc': CalculationType.FIXED, 'desc': 'Up to 24 months moratorium on principal installment repayments.'},
                ],
                'rules': [
                    {'field': 'age', 'op': '>=', 'val': 18, 'desc': 'Applicant must be at least 18 years of age.'},
                    {'field': 'sector', 'op': 'CONTAINS', 'val': 'dairy', 'desc': 'Must pertain to dairy, cattle feed, or animal husbandry value addition.'},
                ],
                'docs': [
                    {'name': 'Comprehensive Dairy / Feed Plant DPR', 'req': RequirementLevel.REQUIRED, 'desc': 'Technical feasibility, milk procurement logistics, equipment schedules.'},
                    {'name': 'Environmental Clearance / Consent to Establish', 'req': RequirementLevel.CONDITIONAL, 'desc': 'State Pollution Control Board NOC for processing plants.'},
                    {'name': 'FSSAI License / Undertaking', 'req': RequirementLevel.REQUIRED, 'desc': 'Food safety compliance certification.'},
                ],
                'steps': [
                    {'step': 1, 'title': 'Online Portal Application', 'desc': 'Register on ahidf.udyamimitra.in and upload project details.'},
                    {'step': 2, 'title': 'DAHD Scrutiny & Approval', 'desc': 'Technical committee scrutinizes milk processing viability and approves application.'},
                    {'step': 3, 'title': 'Bank Credit Processing', 'desc': 'Partner Scheduled Commercial Bank sanctions term loan facility.'},
                    {'step': 4, 'title': 'Disbursement & Subvention Credit', 'desc': 'Loan disbursed in tranches and 3% interest subvention activated.'},
                ]
            },

            # 6. Stand-Up India
            {
                'official_id': 'STAND_UP_INDIA',
                'name': 'Stand-Up India Scheme for SC, ST and Women',
                'short_name': 'Stand-Up India',
                'slug': 'stand-up-india',
                'level': GovernmentLevel.CENTRAL,
                'state': '',
                'ministry': 'Ministry of Finance / Department of Financial Services',
                'department': 'Department of Financial Services',
                'nodal_agency': 'SIDBI & All Scheduled Commercial Banks',
                'category': category_objs['women-shgs'],
                'sectors': ['Greenfield Manufacturing', 'Rural Services', 'Agri-Allied', 'Trading'],
                'description': 'Targeted affirmative institutional credit initiative facilitating bank loans between ₹10 Lakh and ₹1 Crore to at least one SC or ST borrower and at least one woman borrower per bank branch.',
                'short_description': 'Composite institutional bank loans from ₹10 Lakh to ₹1 Crore for SC, ST, and Women entrepreneurs for greenfield ventures.',
                'target_audience': 'Exclusively SC, ST, and Women entrepreneurs setting up greenfield units',
                'official_portal_url': 'https://www.standupmitra.in/',
                'source_name': 'Stand-Up Mitra Portal / SIDBI Guidelines',
                'source_document': 'Stand-Up India Scheme Guidelines (Extended to 2025-26)',
                'source_document_date': datetime.date(2023, 4, 1),
                'last_verified_date': datetime.date(2026, 1, 15),
                'verification_status': VerificationStatus.OFFICIAL,
                'scheme_version': '2026.01',
                'priority_score': 87,
                'keywords': ['stand-up india', 'women entrepreneur', 'sc', 'st', 'greenfield', 'loan', 'sidbi'],
                'fin': {
                    'min_cost': Decimal('1000000.00'),
                    'max_cost': Decimal('10000000.00'),
                    'max_loan': Decimal('8500000.00'),
                    'margin_gen': Decimal('15.00'),
                    'margin_spec': Decimal('15.00'),
                    'sub_gen_urb': Decimal('0.00'),
                    'sub_gen_rur': Decimal('0.00'),
                    'sub_spec_urb': Decimal('0.00'),
                    'sub_spec_rur': Decimal('0.00'),
                    'max_sub': Decimal('0.00'),
                    'timing': SubsidyTiming.UPFRONT,
                    'rate_min': Decimal('8.00'),
                    'rate_max': Decimal('9.50'),
                    'subvention': Decimal('0.00'),
                    'subvention_years': 0,
                    'tenure': 84,
                    'moratorium': 18,
                    'collateral': 'Covered under Credit Guarantee Scheme for Stand-Up India (CGFSI)',
                },
                'benefits': [
                    {'title': 'Composite Loan (Term Loan + Working Capital)', 'type': BenefitType.LOAN_SUPPORT, 'calc': CalculationType.FIXED, 'max': Decimal('10000000.00'), 'primary': True, 'desc': 'Loan covering 85% of project cost (term loan plus working capital limit) between ₹10L and ₹1 Crore.'},
                    {'title': 'Lowest Bank Lending Rate', 'type': BenefitType.LOAN_SUPPORT, 'calc': CalculationType.PERCENTAGE, 'desc': 'Interest capped at MCLR + 3% + Tenor Premium (lowest tier for commercial category).'},
                    {'title': 'Up to 18 Months Moratorium', 'type': BenefitType.LOAN_SUPPORT, 'calc': CalculationType.FIXED, 'desc': 'Repayment holiday up to 18 months during unit stabilization.'},
                ],
                'rules': [
                    {'field': 'age', 'op': '>=', 'val': 18, 'desc': 'Applicant must be at least 18 years old.'},
                    {'field': 'gender', 'op': 'IN', 'val': ['female', 'sc_st'], 'desc': 'Reserved exclusively for Women or SC/ST individual promoters (or 51%+ shareholding in entity).'},
                    {'field': 'business_stage', 'op': 'IN', 'val': ['new'], 'desc': 'Must be a greenfield (first-time venture) enterprise.'},
                ],
                'docs': [
                    {'name': 'Caste Certificate (SC/ST) / Gender Identity Proof', 'req': RequirementLevel.REQUIRED, 'desc': 'Authorized certificate validating affirmative eligibility.'},
                    {'name': 'Greenfield Project Report & Quotations', 'req': RequirementLevel.REQUIRED, 'desc': 'DPR establishing enterprise feasibility.'},
                    {'name': 'Promoter Contribution Proof (15%)', 'req': RequirementLevel.REQUIRED, 'desc': 'Bank balance or sanction of converging Central/State subsidy.'},
                ],
                'steps': [
                    {'step': 1, 'title': 'Stand-Up Mitra Registration', 'desc': 'Register profile on standupmitra.in and indicate handholding support requirements.'},
                    {'step': 2, 'title': 'Application Routing to Preferred Bank', 'desc': 'Application is routed to chosen bank branch or Lead District Manager (LDM).'},
                    {'step': 3, 'title': 'Due Diligence & CIBIL Check', 'desc': 'Bank branch conducts appraisal and verifies greenfield qualification.'},
                    {'step': 4, 'title': 'Sanction & CGFSI Registration', 'desc': 'Bank sanctions composite credit limit and secures guarantee cover through CGFSI.'},
                ]
            },

            # 7. PMMSY
            {
                'official_id': 'PMMSY',
                'name': 'Pradhan Mantri Matsya Sampada Yojana',
                'short_name': 'PMMSY',
                'slug': 'pmmsy',
                'level': GovernmentLevel.CENTRAL,
                'state': '',
                'ministry': 'Ministry of Fisheries, Animal Husbandry and Dairying',
                'department': 'Department of Fisheries',
                'nodal_agency': 'National Fisheries Development Board (NFDB)',
                'category': category_objs['fisheries'],
                'sectors': ['Fish Farming & Aquaculture', 'Biofloc Systems', 'Cold Chain & Reefer Vans', 'Fish Seed Hatcheries'],
                'description': 'Flagship holistic programme to transform fisheries sector through sustainable commercial aquaculture, modern biofloc ponds, hatcheries, and hygienic fish kiosks.',
                'short_description': '40% to 60% capital subsidy (up to ₹30 Lakh) for pond construction, biofloc units, fish seed hatcheries, and cold chain vehicles.',
                'target_audience': 'Fishers, Fish Farmers, Fish Workers, SHGs, JLGs, Agri-Entrepreneurs',
                'official_portal_url': 'https://pmmsy.dof.gov.in/',
                'source_name': 'Department of Fisheries / NFDB Portal',
                'source_document': 'PMMSY Operational Guidelines 2020-25',
                'source_document_date': datetime.date(2020, 5, 20),
                'last_verified_date': datetime.date(2026, 1, 10),
                'verification_status': VerificationStatus.OFFICIAL,
                'scheme_version': '2026.01',
                'priority_score': 85,
                'keywords': ['pmmsy', 'fisheries', 'fish farming', 'biofloc', 'aquaculture', 'subsidy', 'pond'],
                'fin': {
                    'min_cost': Decimal('100000.00'),
                    'max_cost': Decimal('5000000.00'),
                    'max_loan': Decimal('4500000.00'),
                    'margin_gen': Decimal('10.00'),
                    'margin_spec': Decimal('10.00'),
                    'sub_gen_urb': Decimal('40.00'),
                    'sub_gen_rur': Decimal('40.00'),
                    'sub_spec_urb': Decimal('60.00'),
                    'sub_spec_rur': Decimal('60.00'),
                    'max_sub': Decimal('3000000.00'),
                    'timing': SubsidyTiming.BACK_ENDED,
                    'rate_min': Decimal('8.50'),
                    'rate_max': Decimal('10.00'),
                    'subvention': Decimal('0.00'),
                    'subvention_years': 0,
                    'tenure': 84,
                    'moratorium': 6,
                    'collateral': 'Standard bank terms / Credit guarantee cover',
                },
                'benefits': [
                    {'title': '40% to 60% Capital Subsidy', 'type': BenefitType.CAPITAL_SUBSIDY, 'calc': CalculationType.PERCENTAGE, 'pct': Decimal('60.00'), 'max': Decimal('3000000.00'), 'primary': True, 'desc': '40% subsidy for General Category, 60% subsidy for Women and SC/ST beneficiaries.'},
                    {'title': 'Biofloc & RAS Technology Support', 'type': BenefitType.GRANT, 'calc': CalculationType.PERCENTAGE, 'pct': Decimal('60.00'), 'desc': 'Subsidy assistance for high-density recirculating aquaculture systems and solar biofloc setups.'},
                ],
                'rules': [
                    {'field': 'age', 'op': '>=', 'val': 18, 'desc': 'Minimum applicant age is 18 years.'},
                    {'field': 'sector', 'op': 'CONTAINS', 'val': 'fisheries', 'desc': 'Project must be rooted in inland or coastal fisheries/aquaculture.'},
                ],
                'docs': [
                    {'name': 'Land Ownership / Water Body Lease Document (min 7 years)', 'req': RequirementLevel.REQUIRED, 'desc': 'Pond ownership or registered lease agreement.'},
                    {'name': 'Aquaculture DPR', 'req': RequirementLevel.REQUIRED, 'desc': 'Details on fingerling stocking, feed management, and water testing setup.'},
                    {'name': 'Aadhaar Card & Caste/Special Category Certificate', 'req': RequirementLevel.REQUIRED, 'desc': 'Identity and affirmative benefit validation.'},
                ],
                'steps': [
                    {'step': 1, 'title': 'Submit Proposal to District Fisheries Office', 'desc': 'Submit self-contained project proposal to District Fisheries Officer (DFO).'},
                    {'step': 2, 'title': 'District Level Committee (DLC) Clearance', 'desc': 'DLC examines site feasibility and recommends project to State Fisheries Department.'},
                    {'step': 3, 'title': 'Administrative Approval & Bank Sanction', 'desc': 'State Director of Fisheries issues administrative sanction and loan is processed by bank.'},
                    {'step': 4, 'title': 'Geo-Tagged Verification & Subsidy Release', 'desc': 'Field officer inspects completed pond/biofloc installation via mobile app; subsidy credited.'},
                ]
            },

            # 8. PM-KUSUM
            {
                'official_id': 'PM_KUSUM',
                'name': 'Pradhan Mantri Kisan Urja Suraksha evam Utthaan Mahabhiyan',
                'short_name': 'PM-KUSUM',
                'slug': 'pm-kusum',
                'level': GovernmentLevel.CENTRAL,
                'state': '',
                'ministry': 'Ministry of New and Renewable Energy (MNRE)',
                'department': 'Department of Renewable Energy',
                'nodal_agency': 'State Renewable Energy Development Agencies (GEDA, MEDA, etc.)',
                'category': category_objs['renewable-green'],
                'sectors': ['Solar Pumping', 'Green Infrastructure', 'Agro-Photovoltaics', 'Renewable Power'],
                'description': 'National green energy transition scheme providing 60% total financial support (30% Central + 30% State) for off-grid and grid-connected solar agricultural water pumps and decentralized solar plants.',
                'short_description': 'Up to 60% combined subsidy (30% Central + 30% State) for standalone solar pumps and agri-solar power plants.',
                'target_audience': 'Individual Farmers, Groups of Farmers, Water User Associations, FPOs',
                'official_portal_url': 'https://pmkusum.mnre.gov.in/',
                'source_name': 'Ministry of New and Renewable Energy (MNRE) KUSUM Portal',
                'source_document': 'MNRE Notification No. 32/645/2017-SPV',
                'source_document_date': datetime.date(2023, 1, 15),
                'last_verified_date': datetime.date(2026, 1, 8),
                'verification_status': VerificationStatus.OFFICIAL,
                'scheme_version': '2026.01',
                'priority_score': 84,
                'keywords': ['kusum', 'solar pump', 'mnre', 'renewable energy', 'solar plant', 'irrigation subsidy'],
                'fin': {
                    'min_cost': Decimal('150000.00'),
                    'max_cost': Decimal('3000000.00'),
                    'max_loan': Decimal('2100000.00'),
                    'margin_gen': Decimal('10.00'),
                    'margin_spec': Decimal('10.00'),
                    'sub_gen_urb': Decimal('30.00'),
                    'sub_gen_rur': Decimal('60.00'),
                    'sub_spec_urb': Decimal('30.00'),
                    'sub_spec_rur': Decimal('60.00'),
                    'max_sub': Decimal('1800000.00'),
                    'timing': SubsidyTiming.UPFRONT,
                    'rate_min': Decimal('7.50'),
                    'rate_max': Decimal('9.00'),
                    'subvention': Decimal('0.00'),
                    'subvention_years': 0,
                    'tenure': 60,
                    'moratorium': 3,
                    'collateral': 'Hypothecation of solar pump asset',
                },
                'benefits': [
                    {'title': '60% Combined Capital Subsidy', 'type': BenefitType.CAPITAL_SUBSIDY, 'calc': CalculationType.PERCENTAGE, 'pct': Decimal('60.00'), 'max': Decimal('1800000.00'), 'primary': True, 'desc': '30% Central Financial Assistance (CFA) + 30% State Government subsidy.'},
                    {'title': 'Only 10% Farmer Contribution', 'type': BenefitType.LOAN_SUPPORT, 'calc': CalculationType.PERCENTAGE, 'pct': Decimal('10.00'), 'desc': 'Beneficiary pays only 10% upfront; remaining 30% can be financed via bank loan.'},
                ],
                'rules': [
                    {'field': 'age', 'op': '>=', 'val': 18, 'desc': 'Applicant must be at least 18 years of age.'},
                    {'field': 'rural_urban', 'op': 'IN', 'val': ['rural'], 'desc': 'Installation must be in rural agricultural location.'},
                ],
                'docs': [
                    {'name': 'Farmland Land Record (7/12, 8A / RoR)', 'req': RequirementLevel.REQUIRED, 'desc': 'Proof of agricultural land possession.'},
                    {'name': 'Water Source Certification / Borewell Proof', 'req': RequirementLevel.REQUIRED, 'desc': 'Presence of functional well, borewell, or canal link.'},
                    {'name': 'Aadhaar & Bank Passbook', 'req': RequirementLevel.REQUIRED, 'desc': 'For direct subsidy link.'},
                ],
                'steps': [
                    {'step': 1, 'title': 'Register on State Nodal Portal', 'desc': 'Apply online on State Renewable Agency portal (e.g. GEDA / MEDA).'},
                    {'step': 2, 'title': 'Demand Notice & Farmer Share Payment', 'desc': 'Deposit 10% beneficiary margin into the designated escrow account upon verification.'},
                    {'step': 3, 'title': 'Empanelled Vendor Installation', 'desc': 'Authorized MNRE empanelled vendor delivers and commissions solar pump system.'},
                    {'step': 4, 'title': 'Inspection & Subsidy Adjustment', 'desc': 'Joint inspection confirms working flow; 60% government subsidy settled directly with vendor.'},
                ]
            },

            # 9. State: Gujarat - MMUY
            {
                'official_id': 'MMUY_GUJ',
                'name': 'Mukhyamantri Mahila Utkarsh Yojana',
                'short_name': 'MMUY (Gujarat)',
                'slug': 'mmuy-gujarat',
                'level': GovernmentLevel.STATE,
                'state': 'Gujarat',
                'ministry': 'Women & Child Development Department, Govt of Gujarat',
                'department': 'Gujarat Livelihood Promotion Company (GLPC)',
                'nodal_agency': 'GLPC & District Rural Development Agency (DRDA)',
                'category': category_objs['women-shgs'],
                'sectors': ['Women SHG Enterprise', 'Rural Retail', 'Food & Handicraft', 'Cottage Industries'],
                'description': 'Flagship Gujarat state welfare scheme providing 100% interest-free loans (0% interest rate) up to ₹1 Lakh per woman member in Joint Liability Earning Groups (JLEGs) of 10 women, with state government bearing all interest charges.',
                'short_description': '100% interest-free loan (0% interest) up to ₹1,00,000 for rural women SHGs in Gujarat.',
                'target_audience': 'Women Self-Help Groups (SHGs) and Joint Liability Earning Groups (JLEGs) in Gujarat',
                'official_portal_url': 'https://schemes.gujarat.gov.in/',
                'source_name': 'Govt of Gujarat Women & Child Development Portal',
                'source_document': 'Govt of Gujarat Resolution No. WCD/102020/MMUY',
                'source_document_date': datetime.date(2020, 9, 17),
                'last_verified_date': datetime.date(2026, 1, 14),
                'verification_status': VerificationStatus.OFFICIAL,
                'scheme_version': '2026.01',
                'priority_score': 94,
                'keywords': ['mmuy', 'gujarat', 'women', 'shg', '0% interest', 'interest-free', 'mahila utkarsh'],
                'fin': {
                    'min_cost': Decimal('20000.00'),
                    'max_cost': Decimal('1000000.00'),
                    'max_loan': Decimal('1000000.00'),
                    'margin_gen': Decimal('0.00'),
                    'margin_spec': Decimal('0.00'),
                    'sub_gen_urb': Decimal('0.00'),
                    'sub_gen_rur': Decimal('0.00'),
                    'sub_spec_urb': Decimal('0.00'),
                    'sub_spec_rur': Decimal('0.00'),
                    'max_sub': Decimal('0.00'),
                    'timing': SubsidyTiming.UPFRONT,
                    'rate_min': Decimal('0.00'),
                    'rate_max': Decimal('0.00'),
                    'subvention': Decimal('100.00'),
                    'subvention_years': 3,
                    'tenure': 36,
                    'moratorium': 3,
                    'collateral': 'Zero collateral required',
                },
                'benefits': [
                    {'title': '100% Interest Subvention (0% Net Interest)', 'type': BenefitType.INTEREST_SUBVENTION, 'calc': CalculationType.INTEREST_SPREAD, 'pct': Decimal('100.00'), 'primary': True, 'desc': 'Gujarat State Government bears the entire annual interest burden directly with banks.'},
                    {'title': 'Zero Promoter Equity Required', 'type': BenefitType.LOAN_SUPPORT, 'calc': CalculationType.PERCENTAGE, 'pct': Decimal('100.00'), 'desc': '100% of the loan amount is disbursed without demanding own contribution.'},
                    {'title': 'Stamp Duty & Processing Fee Waiver', 'type': BenefitType.GRANT, 'calc': CalculationType.FIXED, 'desc': 'Complete exemption from stamp duty charges and loan processing fees.'},
                ],
                'rules': [
                    {'field': 'state', 'op': '=', 'val': 'Gujarat', 'desc': 'Applicant must reside and operate enterprise within Gujarat state.'},
                    {'field': 'gender', 'op': '=', 'val': 'female', 'desc': 'Exclusively restricted to women entrepreneurs / SHG members.'},
                    {'field': 'age', 'op': 'BETWEEN', 'val': {'min': 18, 'max': 59}, 'desc': 'Age must be between 18 and 59 years.'},
                ],
                'docs': [
                    {'name': 'Gujarat Resident Proof & Aadhaar', 'req': RequirementLevel.REQUIRED, 'desc': 'Proof of domicile in Gujarat.'},
                    {'name': 'JLEG / SHG Member Resolution & Bank Account', 'req': RequirementLevel.REQUIRED, 'desc': 'Joint group resolution letter and active group bank account.'},
                    {'name': 'Income Certificate / BPL Card / Antyodaya Proof', 'req': RequirementLevel.CONDITIONAL, 'desc': 'To establish socio-economic priority.'},
                ],
                'steps': [
                    {'step': 1, 'title': 'Form JLEG Group of 10 Women', 'desc': 'Form a mutual liability group of 10 women with GLPC field facilitator assistance.'},
                    {'step': 2, 'title': 'Submit Application to Taluka GLPC Officer', 'desc': 'Submit group application with KYC proofs to Taluka Development Officer / GLPC coordinator.'},
                    {'step': 3, 'title': 'Direct Bank Disbursement', 'desc': 'Designated bank disburses loan up to ₹1,00,000 per member directly into joint bank accounts.'},
                    {'step': 4, 'title': 'Interest Subsidy Reimbursement', 'desc': 'Borrowers pay only principal in regular monthly installments; Gujarat Govt credits interest.'},
                ]
            },

            # 10. State: Gujarat - GAIC Agro Policy
            {
                'official_id': 'GAIC_GUJ',
                'name': 'Gujarat Comprehensive Agro-Industrial Policy Subsidy',
                'short_name': 'GAIC Agro Subsidy',
                'slug': 'gaic-agro-subsidy',
                'level': GovernmentLevel.STATE,
                'state': 'Gujarat',
                'ministry': 'Agriculture, Farmers Welfare & Co-operation Department, Govt of Gujarat',
                'department': 'Directorate of Horticulture & Agriculture',
                'nodal_agency': 'Gujarat Agro Industries Corporation (GAIC)',
                'category': category_objs['agriculture-food'],
                'sectors': ['Food & Agro Processing', 'Cold Storage', 'Oil Extraction', 'Spice Processing'],
                'description': 'Comprehensive state policy providing 25% capital investment subsidy up to ₹50 Lakh plus 7.5% interest subsidy for 5 years on term loans for agro-food processing enterprises in Gujarat.',
                'short_description': '25% capital subsidy up to ₹50 Lakh + 7.5% annual interest subsidy for 5 years for agro-processing in Gujarat.',
                'target_audience': 'Agro-processing entrepreneurs, FPOs, food factory setups in Gujarat',
                'official_portal_url': 'https://gaic.gujarat.gov.in/',
                'source_name': 'Gujarat Agro Industries Corporation (GAIC) Portal',
                'source_document': 'Govt of Gujarat Agro-Industrial Policy Resolution 2020-25',
                'source_document_date': datetime.date(2020, 8, 10),
                'last_verified_date': datetime.date(2026, 1, 12),
                'verification_status': VerificationStatus.OFFICIAL,
                'scheme_version': '2026.01',
                'priority_score': 91,
                'keywords': ['gaic', 'gujarat', 'agro subsidy', 'food processing', 'capital subsidy', 'groundnut oil', 'cotton processing'],
                'fin': {
                    'min_cost': Decimal('1000000.00'),
                    'max_cost': Decimal('50000000.00'),
                    'max_loan': Decimal('45000000.00'),
                    'margin_gen': Decimal('10.00'),
                    'margin_spec': Decimal('10.00'),
                    'sub_gen_urb': Decimal('25.00'),
                    'sub_gen_rur': Decimal('25.00'),
                    'sub_spec_urb': Decimal('25.00'),
                    'sub_spec_rur': Decimal('25.00'),
                    'max_sub': Decimal('5000000.00'),
                    'timing': SubsidyTiming.BACK_ENDED,
                    'rate_min': Decimal('7.50'),
                    'rate_max': Decimal('9.50'),
                    'subvention': Decimal('7.50'),
                    'subvention_years': 5,
                    'tenure': 84,
                    'moratorium': 12,
                    'collateral': 'Bank standard terms / Hypothecation of machinery',
                },
                'benefits': [
                    {'title': '25% Capital Investment Subsidy', 'type': BenefitType.CAPITAL_SUBSIDY, 'calc': CalculationType.PERCENTAGE, 'pct': Decimal('25.00'), 'max': Decimal('5000000.00'), 'primary': True, 'desc': '25% subsidy on eligible plant and machinery up to ₹50 Lakh.'},
                    {'title': '7.5% Annual Term Loan Interest Subsidy', 'type': BenefitType.INTEREST_SUBVENTION, 'calc': CalculationType.INTEREST_SPREAD, 'pct': Decimal('7.50'), 'desc': 'Up to 7.5% interest subvention per annum for 5 years on term loans (capped at ₹1 Crore).'},
                    {'title': 'Electricity Duty Exemption', 'type': BenefitType.GRANT, 'calc': CalculationType.FIXED, 'desc': '100% exemption from payment of electricity duty for 5 continuous years.'},
                ],
                'rules': [
                    {'field': 'state', 'op': '=', 'val': 'Gujarat', 'desc': 'Enterprise must be established within the state of Gujarat.'},
                    {'field': 'sector', 'op': 'CONTAINS', 'val': 'agro', 'desc': 'Must be engaged in agro, horticultural, or food processing operations.'},
                ],
                'docs': [
                    {'name': 'Gujarat Industrial Land / Shed Document', 'req': RequirementLevel.REQUIRED, 'desc': 'Proof of factory land or GIDC allotment in Gujarat.'},
                    {'name': 'Technical DPR & Quotations for Processing Machinery', 'req': RequirementLevel.REQUIRED, 'desc': 'Itemized equipment invoice quotations.'},
                    {'name': 'Bank Term Loan Sanction Letter', 'req': RequirementLevel.REQUIRED, 'desc': 'Copy of formal loan sanction from a bank in Gujarat.'},
                ],
                'steps': [
                    {'step': 1, 'title': 'Online Portal Registration with GAIC', 'desc': 'Apply online at gaic.gujarat.gov.in before commencing commercial production.'},
                    {'step': 2, 'title': 'Field Inspection by GAIC Engineers', 'desc': 'Technical inspection of installed machinery and expenditure invoices.'},
                    {'step': 3, 'title': 'Sanction Committee Endorsement', 'desc': 'State Level Sanctioning Committee approves subsidy quantum.'},
                    {'step': 4, 'title': 'Subsidy Disbursal to Bank Account', 'desc': 'Capital subsidy and interest rebates credited to lending bank account.'},
                ]
            },

            # 11. State: Gujarat - Shri Vajpayee Bankable
            {
                'official_id': 'VBY_GUJ',
                'name': 'Shri Vajpayee Bankable Yojana',
                'short_name': 'VBY (Gujarat)',
                'slug': 'vby-gujarat',
                'level': GovernmentLevel.STATE,
                'state': 'Gujarat',
                'ministry': 'Industries and Mines Department, Govt of Gujarat',
                'department': 'Commissioner of Cottage and Rural Industries',
                'nodal_agency': 'District Industries Centre (DIC) Gujarat',
                'category': category_objs['handicraft-artisan'],
                'sectors': ['Cottage Industries', 'Handicrafts & Artisans', 'Rural Services', 'Small Manufacturing'],
                'description': 'Self-employment scheme in Gujarat offering 20% to 40% capital subsidies for rural artisans, traditional craftsmen, cottage units, and service entrepreneurs with special assistance for women, SC, ST, and Divyang.',
                'short_description': '20% to 40% capital subsidy (up to ₹1,25,000) for rural artisans, cottage units, and small businesses in Gujarat.',
                'target_audience': 'Rural Artisans, Women, SC/ST, Divyang, Cottage entrepreneurs in Gujarat (Age 18-65)',
                'official_portal_url': 'https://cottage.gujarat.gov.in/',
                'source_name': 'Cottage and Rural Industries Department, Govt of Gujarat',
                'source_document': 'Govt Resolution No. COT/102012/367/CH',
                'source_document_date': datetime.date(2021, 6, 1),
                'last_verified_date': datetime.date(2026, 1, 12),
                'verification_status': VerificationStatus.OFFICIAL,
                'scheme_version': '2026.01',
                'priority_score': 89,
                'keywords': ['vby', 'vajpayee bankable', 'gujarat', 'artisan', 'cottage industry', 'subsidy', 'dic'],
                'fin': {
                    'min_cost': Decimal('25000.00'),
                    'max_cost': Decimal('800000.00'),
                    'max_loan': Decimal('760000.00'),
                    'margin_gen': Decimal('10.00'),
                    'margin_spec': Decimal('5.00'),
                    'sub_gen_urb': Decimal('20.00'),
                    'sub_gen_rur': Decimal('25.00'),
                    'sub_spec_urb': Decimal('30.00'),
                    'sub_spec_rur': Decimal('40.00'),
                    'max_sub': Decimal('125000.00'),
                    'timing': SubsidyTiming.BACK_ENDED,
                    'rate_min': Decimal('8.50'),
                    'rate_max': Decimal('10.50'),
                    'subvention': Decimal('0.00'),
                    'subvention_years': 0,
                    'tenure': 60,
                    'moratorium': 6,
                    'collateral': 'Collateral-free loan',
                },
                'benefits': [
                    {'title': 'Up to 40% Capital Subsidy', 'type': BenefitType.CAPITAL_SUBSIDY, 'calc': CalculationType.PERCENTAGE, 'pct': Decimal('40.00'), 'max': Decimal('125000.00'), 'primary': True, 'desc': 'Up to ₹1,25,000 for Special/Rural categories (Women, SC/ST/Divyang) and up to ₹1,00,000 for General.'},
                    {'title': 'Low Own Margin (5%)', 'type': BenefitType.LOAN_SUPPORT, 'calc': CalculationType.PERCENTAGE, 'pct': Decimal('95.00'), 'desc': 'Promoter invests only 5% of project cost for special categories.'},
                ],
                'rules': [
                    {'field': 'state', 'op': '=', 'val': 'Gujarat', 'desc': 'Applicant must be a permanent resident of Gujarat.'},
                    {'field': 'age', 'op': 'BETWEEN', 'val': {'min': 18, 'max': 65}, 'desc': 'Age must be between 18 and 65 years.'},
                ],
                'docs': [
                    {'name': 'Gujarat Domicile / Ration Card & Aadhaar', 'req': RequirementLevel.REQUIRED, 'desc': 'Address and residency proofs.'},
                    {'name': 'Artisan Card / Technical Qualification (if any)', 'req': RequirementLevel.CONDITIONAL, 'desc': 'Proof of skill training or experience in chosen trade.'},
                    {'name': 'Caste / Divyang Certificate', 'req': RequirementLevel.CONDITIONAL, 'desc': 'To claim 40% subsidy ceiling.'},
                ],
                'steps': [
                    {'step': 1, 'title': 'Apply on e-Kutir Portal', 'desc': 'Submit online application at cottage.gujarat.gov.in.'},
                    {'step': 2, 'title': 'DIC Scrutiny & Interview', 'desc': 'District Industries Centre interviews applicant and verifies credentials.'},
                    {'step': 3, 'title': 'Bank Loan Disbursement & Subsidy Credit', 'desc': 'Bank disburses loan; DIC releases subsidy into 3-year locked deposit.'},
                ]
            },

            # 12. State: Maharashtra - CMEGP
            {
                'official_id': 'CMEGP_MAH',
                'name': 'Chief Minister Employment Generation Programme',
                'short_name': 'CMEGP (Maharashtra)',
                'slug': 'cmegp-maharashtra',
                'level': GovernmentLevel.STATE,
                'state': 'Maharashtra',
                'ministry': 'Industries Department, Govt of Maharashtra',
                'department': 'Directorate of Industries',
                'nodal_agency': 'Maharashtra KVIB & District Industries Centres (DIC)',
                'category': category_objs['msme-manufacturing'],
                'sectors': ['Manufacturing', 'Food Processing', 'Agro-Allied', 'Rural Services'],
                'description': 'Maharashtra flagship credit-linked subsidy programme providing 15% to 35% margin money assistance (up to ₹17.5 Lakh) for projects up to ₹50 Lakh in manufacturing and ₹20 Lakh in service sectors.',
                'short_description': '15% to 35% capital subsidy (up to ₹17.5 Lakh) for rural manufacturing and services in Maharashtra.',
                'target_audience': 'Educated unemployed youth, rural entrepreneurs in Maharashtra (Age 18-45)',
                'official_portal_url': 'https://maha-cmegp.gov.in/',
                'source_name': 'Govt of Maharashtra CMEGP Portal',
                'source_document': 'Govt Resolution No. CMEGP-2019/CR-14/IND-7',
                'source_document_date': datetime.date(2019, 8, 1),
                'last_verified_date': datetime.date(2026, 1, 10),
                'verification_status': VerificationStatus.OFFICIAL,
                'scheme_version': '2026.01',
                'priority_score': 88,
                'keywords': ['cmegp', 'maharashtra', 'subsidy', 'manufacturing', 'dic', 'employment generation'],
                'fin': {
                    'min_cost': Decimal('100000.00'),
                    'max_cost': Decimal('5000000.00'),
                    'max_loan': Decimal('4750000.00'),
                    'margin_gen': Decimal('10.00'),
                    'margin_spec': Decimal('5.00'),
                    'sub_gen_urb': Decimal('15.00'),
                    'sub_gen_rur': Decimal('25.00'),
                    'sub_spec_urb': Decimal('25.00'),
                    'sub_spec_rur': Decimal('35.00'),
                    'max_sub': Decimal('1750000.00'),
                    'timing': SubsidyTiming.BACK_ENDED,
                    'rate_min': Decimal('8.50'),
                    'rate_max': Decimal('10.50'),
                    'subvention': Decimal('0.00'),
                    'subvention_years': 0,
                    'tenure': 84,
                    'moratorium': 6,
                    'collateral': 'Collateral-free via CGTMSE',
                },
                'benefits': [
                    {'title': 'Up to 35% Margin Money Subsidy', 'type': BenefitType.CAPITAL_SUBSIDY, 'calc': CalculationType.PERCENTAGE, 'pct': Decimal('35.00'), 'max': Decimal('1750000.00'), 'primary': True, 'desc': '25% to 35% in rural areas for special categories (SC/ST/Women/OBC/Minority).'},
                    {'title': 'CGTMSE Guarantee Fee Paid by State', 'type': BenefitType.CREDIT_GUARANTEE, 'calc': CalculationType.PERCENTAGE, 'pct': Decimal('100.00'), 'desc': 'Guarantee fees borne by Govt of Maharashtra.'},
                ],
                'rules': [
                    {'field': 'state', 'op': '=', 'val': 'Maharashtra', 'desc': 'Applicant must be a permanent resident of Maharashtra.'},
                    {'field': 'age', 'op': 'BETWEEN', 'val': {'min': 18, 'max': 45}, 'desc': 'Age must be between 18 and 45 years (up to 50 for SC/ST/Women).'},
                ],
                'docs': [
                    {'name': 'Maharashtra Domicile Certificate', 'req': RequirementLevel.REQUIRED, 'desc': 'Proof of residency in Maharashtra.'},
                    {'name': 'Detailed Project Report (DPR)', 'req': RequirementLevel.REQUIRED, 'desc': 'Complete financial viability report.'},
                    {'name': 'Educational Qualification Proof (min 7th pass)', 'req': RequirementLevel.REQUIRED, 'desc': 'Academic school leaving or passing mark sheet.'},
                ],
                'steps': [
                    {'step': 1, 'title': 'Register on maha-cmegp.gov.in', 'desc': 'Submit online proposal on the Maharashtra state portal.'},
                    {'step': 2, 'title': 'District Task Force Committee (DTFC) Approval', 'desc': 'DTFC chaired by District Collector clears project proposal.'},
                    {'step': 3, 'title': 'Bank Sanction & EDP Training', 'desc': 'Bank issues sanction letter; candidate completes mandatory EDP training.'},
                    {'step': 4, 'title': 'Subsidy Disbursal into TDR', 'desc': 'Subsidy credited into a 3-year term deposit receipt.'},
                ]
            },

            # 13. State: Uttar Pradesh - MYSY
            {
                'official_id': 'MSY_UP',
                'name': 'Mukhyamantri Yuva Swarojgar Yojana',
                'short_name': 'MYSY (Uttar Pradesh)',
                'slug': 'mysy-uttar-pradesh',
                'level': GovernmentLevel.STATE,
                'state': 'Uttar Pradesh',
                'ministry': 'Department of MSME & Export Promotion, Govt of Uttar Pradesh',
                'department': 'Directorate of Industries',
                'nodal_agency': 'District Industries Centre (DIC) UP',
                'category': category_objs['msme-manufacturing'],
                'sectors': ['Micro Manufacturing', 'Agro-Processing', 'Rural Services', 'Packaging'],
                'description': 'UP government self-employment scheme providing 25% margin money subsidy (up to ₹6.25 Lakh for manufacturing up to ₹25 Lakh, and up to ₹2.5 Lakh for services up to ₹10 Lakh) to educated youth.',
                'short_description': '25% margin money subsidy up to ₹6.25 Lakh for industrial units in Uttar Pradesh.',
                'target_audience': 'Educated youth residing in Uttar Pradesh (Age 18-40)',
                'official_portal_url': 'https://diupmsme.upsdc.gov.in/',
                'source_name': 'Department of MSME, Govt of Uttar Pradesh',
                'source_document': 'Govt of UP MSME Order No. 420/2018/18-2-18',
                'source_document_date': datetime.date(2018, 4, 1),
                'last_verified_date': datetime.date(2026, 1, 8),
                'verification_status': VerificationStatus.OFFICIAL,
                'scheme_version': '2026.01',
                'priority_score': 86,
                'keywords': ['mysy', 'uttar pradesh', 'up msme', 'subsidy', 'yuva swarojgar', 'dic up'],
                'fin': {
                    'min_cost': Decimal('100000.00'),
                    'max_cost': Decimal('2500000.00'),
                    'max_loan': Decimal('2250000.00'),
                    'margin_gen': Decimal('10.00'),
                    'margin_spec': Decimal('10.00'),
                    'sub_gen_urb': Decimal('25.00'),
                    'sub_gen_rur': Decimal('25.00'),
                    'sub_spec_urb': Decimal('25.00'),
                    'sub_spec_rur': Decimal('25.00'),
                    'max_sub': Decimal('625000.00'),
                    'timing': SubsidyTiming.BACK_ENDED,
                    'rate_min': Decimal('8.50'),
                    'rate_max': Decimal('10.50'),
                    'subvention': Decimal('0.00'),
                    'subvention_years': 0,
                    'tenure': 84,
                    'moratorium': 6,
                    'collateral': 'Collateral-free through CGTMSE',
                },
                'benefits': [
                    {'title': '25% Margin Money Capital Subsidy', 'type': BenefitType.CAPITAL_SUBSIDY, 'calc': CalculationType.PERCENTAGE, 'pct': Decimal('25.00'), 'max': Decimal('625000.00'), 'primary': True, 'desc': 'Up to ₹6,25,000 for industry units and up to ₹2,50,000 for service units.'},
                ],
                'rules': [
                    {'field': 'state', 'op': '=', 'val': 'Uttar Pradesh', 'desc': 'Applicant must be a permanent resident of Uttar Pradesh.'},
                    {'field': 'age', 'op': 'BETWEEN', 'val': {'min': 18, 'max': 40}, 'desc': 'Age must be between 18 and 40 years.'},
                    {'field': 'education', 'op': '>=', 'val': '10th', 'desc': 'Minimum educational qualification is High School (10th pass).'},
                ],
                'docs': [
                    {'name': 'UP Domicile & High School (10th) Passing Certificate', 'req': RequirementLevel.REQUIRED, 'desc': 'Proof of state residency and minimum educational qualification.'},
                    {'name': 'Detailed Project Report (DPR)', 'req': RequirementLevel.REQUIRED, 'desc': 'Technical setup and revenue forecast.'},
                    {'name': 'Affidavit of Non-Default in Any Bank', 'req': RequirementLevel.REQUIRED, 'desc': 'Notarized undertaking of clean banking record.'},
                ],
                'steps': [
                    {'step': 1, 'title': 'Online Registration on diupmsme.upsdc.gov.in', 'desc': 'Fill out online application form.'},
                    {'step': 2, 'title': 'District Task Force Committee Interview', 'desc': 'Interview by DTFC chaired by Deputy Commissioner DIC.'},
                    {'step': 3, 'title': 'Bank Credit Sanction', 'desc': 'Lending bank sanctions term loan and releases initial tranche.'},
                    {'step': 4, 'title': 'Subsidy Released into 2-Year TDR', 'desc': 'DIC credits 25% subsidy into 2-year locked TDR account.'},
                ]
            },

            # 14. State: Rajasthan - MLUPY
            {
                'official_id': 'MLUPY_RAJ',
                'name': 'Mukhyamantri Laghu Udyog Protsahan Yojana',
                'short_name': 'MLUPY (Rajasthan)',
                'slug': 'mlupy-rajasthan',
                'level': GovernmentLevel.STATE,
                'state': 'Rajasthan',
                'ministry': 'Industries & Commerce Department, Govt of Rajasthan',
                'department': 'Directorate of Industries',
                'nodal_agency': 'District Industries Centres (DIC) Rajasthan',
                'category': category_objs['msme-manufacturing'],
                'sectors': ['Manufacturing', 'Services', 'Agro-Processing', 'Rural Retail'],
                'description': 'Rajasthan premier enterprise credit scheme providing tiered annual interest subventions up to 8% for 5 years on loans up to ₹10 Crore for setting up new micro, small and medium enterprises.',
                'short_description': '5% to 8% annual interest subvention for 5 years on institutional loans up to ₹10 Crore in Rajasthan.',
                'target_audience': 'Entrepreneurs, artisans, service providers in Rajasthan (Age 18+)',
                'official_portal_url': 'https://industries.rajasthan.gov.in/',
                'source_name': 'Industries Department, Govt of Rajasthan',
                'source_document': 'Govt of Rajasthan Notification No. F.7(1)Ind./2/2019',
                'source_document_date': datetime.date(2019, 12, 13),
                'last_verified_date': datetime.date(2026, 1, 8),
                'verification_status': VerificationStatus.OFFICIAL,
                'scheme_version': '2026.01',
                'priority_score': 87,
                'keywords': ['mlupy', 'rajasthan', 'interest subvention', 'msme', 'dic rajasthan', 'laghu udyog'],
                'fin': {
                    'min_cost': Decimal('100000.00'),
                    'max_cost': Decimal('100000000.00'),
                    'max_loan': Decimal('100000000.00'),
                    'margin_gen': Decimal('10.00'),
                    'margin_spec': Decimal('10.00'),
                    'sub_gen_urb': Decimal('0.00'),
                    'sub_gen_rur': Decimal('0.00'),
                    'sub_spec_urb': Decimal('0.00'),
                    'sub_spec_rur': Decimal('0.00'),
                    'max_sub': Decimal('0.00'),
                    'timing': SubsidyTiming.BACK_ENDED,
                    'rate_min': Decimal('5.00'),
                    'rate_max': Decimal('8.00'),
                    'subvention': Decimal('8.00'),
                    'subvention_years': 5,
                    'tenure': 84,
                    'moratorium': 6,
                    'collateral': 'Collateral-free up to ₹10 Lakh / Standard bank norms',
                },
                'benefits': [
                    {'title': 'Tiered Interest Subvention up to 8% for 5 Years', 'type': BenefitType.INTEREST_SUBVENTION, 'calc': CalculationType.INTEREST_SPREAD, 'pct': Decimal('8.00'), 'primary': True, 'desc': '8% on loans up to ₹25 Lakh, 6% on loans ₹25L to ₹5 Crore, 5% on loans ₹5 Cr to ₹10 Crore.'},
                ],
                'rules': [
                    {'field': 'state', 'op': '=', 'val': 'Rajasthan', 'desc': 'Enterprise must be established within Rajasthan state.'},
                    {'field': 'age', 'op': '>=', 'val': 18, 'desc': 'Applicant must be at least 18 years of age.'},
                ],
                'docs': [
                    {'name': 'Rajasthan Domicile / Jan Aadhaar Card', 'req': RequirementLevel.REQUIRED, 'desc': 'Proof of identity and state residence via Jan Aadhaar.'},
                    {'name': 'Detailed Project Report (DPR)', 'req': RequirementLevel.REQUIRED, 'desc': 'Complete business proposal.'},
                    {'name': 'Bank Loan Sanction Letter', 'req': RequirementLevel.REQUIRED, 'desc': 'From commercial/co-operative bank in Rajasthan.'},
                ],
                'steps': [
                    {'step': 1, 'title': 'Online Application via SSO Portal', 'desc': 'Apply through Rajasthan Single Sign On (sso.rajasthan.gov.in) under MLUPY service.'},
                    {'step': 2, 'title': 'DIC Forwarding to Bank', 'desc': 'District Industries Centre verifies profile and forwards application to selected bank.'},
                    {'step': 3, 'title': 'Quarterly Subvention Reimbursement', 'desc': 'State Govt reimburses interest subvention quantum directly to lending bank each quarter.'},
                ]
            }
        ]

        for s_data in schemes_data:
            scheme, created = GovtScheme.objects.update_or_create(
                official_id=s_data['official_id'],
                defaults={
                    'name': s_data['name'],
                    'short_name': s_data['short_name'],
                    'slug': s_data['slug'],
                    'level': s_data['level'],
                    'state': s_data['state'],
                    'ministry': s_data['ministry'],
                    'department': s_data['department'],
                    'nodal_agency': s_data['nodal_agency'],
                    'category': s_data['category'],
                    'sectors': s_data['sectors'],
                    'description': s_data['description'],
                    'short_description': s_data['short_description'],
                    'target_audience': s_data['target_audience'],
                    'status': SchemeStatus.ACTIVE,
                    'official_portal_url': s_data['official_portal_url'],
                    'source_name': s_data['source_name'],
                    'source_document': s_data['source_document'],
                    'source_document_date': s_data['source_document_date'],
                    'last_verified_date': s_data['last_verified_date'],
                    'verification_status': s_data['verification_status'],
                    'scheme_version': s_data['scheme_version'],
                    'priority_score': s_data['priority_score'],
                    'keywords': s_data['keywords'],
                }
            )

            # Financial Rule
            fin = s_data['fin']
            SchemeFinancialRule.objects.update_or_create(
                scheme=scheme,
                defaults={
                    'min_project_cost': fin['min_cost'],
                    'max_project_cost': fin['max_cost'],
                    'max_loan_amount': fin['max_loan'],
                    'min_promoter_margin_pct': fin['margin_gen'],
                    'promoter_margin_special_pct': fin['margin_spec'],
                    'subsidy_rate_general_urban': fin['sub_gen_urb'],
                    'subsidy_rate_general_rural': fin['sub_gen_rur'],
                    'subsidy_rate_special_urban': fin['sub_spec_urb'],
                    'subsidy_rate_special_rural': fin['sub_spec_rur'],
                    'max_subsidy_amount': fin['max_sub'],
                    'subsidy_timing': fin['timing'],
                    'interest_rate_min': fin['rate_min'],
                    'interest_rate_max': fin['rate_max'],
                    'interest_subvention_pct': fin['subvention'],
                    'subvention_tenure_years': fin['subvention_years'],
                    'tenure_months_max': fin['tenure'],
                    'moratorium_months_max': fin['moratorium'],
                    'collateral_type': fin['collateral'],
                }
            )

            # Benefits
            scheme.benefits.all().delete()
            for b in s_data['benefits']:
                SchemeBenefit.objects.create(
                    scheme=scheme,
                    title=b['title'],
                    benefit_type=b['type'],
                    calculation_type=b.get('calc', CalculationType.PERCENTAGE),
                    percentage=b.get('pct'),
                    fixed_amount=b.get('fixed'),
                    max_amount=b.get('max'),
                    is_primary=b.get('primary', False),
                    conditions=b.get('desc', '')
                )

            # Eligibility Rules
            scheme.eligibility_rules.all().delete()
            for r in s_data['rules']:
                SchemeEligibilityRule.objects.create(
                    scheme=scheme,
                    field=r['field'],
                    operator=r['op'],
                    expected_value=r['val'],
                    rule_description=r['desc'],
                    is_mandatory=True
                )

            # Documents
            scheme.documents.all().delete()
            for idx, doc in enumerate(s_data['docs']):
                SchemeDocument.objects.create(
                    scheme=scheme,
                    name=doc['name'],
                    requirement_level=doc['req'],
                    description=doc.get('desc', ''),
                    sort_order=idx + 1
                )

            # Application Steps
            scheme.application_steps.all().delete()
            for step in s_data['steps']:
                SchemeApplicationStep.objects.create(
                    scheme=scheme,
                    step_number=step['step'],
                    title=step['title'],
                    description=step['desc'],
                    portal_url=step.get('portal', scheme.official_portal_url)
                )

            status_str = "Created" if created else "Updated"
            self.stdout.write(f"  [{status_str}] {scheme.short_name} ({scheme.get_level_display()})")

        self.stdout.write(self.style.SUCCESS(f"Successfully seeded {len(schemes_data)} verified government schemes!"))
