# Generated by Django 5.2.17 on 2026-09-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_interest',
            field=models.CharField(blank=True, help_text='General business interest category (not tied to any specific assessment)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='entrepreneur_type',
            field=models.CharField(blank=True, choices=[('aspiring', 'Aspiring Entrepreneur'), ('new', 'New Entrepreneur'), ('existing', 'Existing Entrepreneur')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.CharField(blank=True, choices=[('none', 'No experience'), ('lt1', 'Less than 1 year'), ('1_3', '1–3 years'), ('3_5', '3–5 years'), ('gt5', 'More than 5 years')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='own_capital',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Approximate own capital available in INR', max_digits=12, null=True),
        ),
    ]
