# Generated by Django 5.2.17 on 2026-09-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_block',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
