# Generated by Django 5.2.17 on 2026-09-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_phoneverificationotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneverificationotp',
            name='otp',
        ),
        migrations.AddField(
            model_name='phoneverificationotp',
            name='attempts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phoneverificationotp',
            name='last_sent_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='phoneverificationotp',
            name='otp_hash',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='phoneverificationotp',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
