# Generated by Django 5.2.17 on 2026-09-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_phoneverificationotp_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
