# Generated by Django 5.2.17 on 2026-09-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
