# Generated by Django 5.2.17 on 2026-09-09 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AsuseEnterpriseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("indicator", models.CharField(max_length=255)),
                ("frequency", models.CharField(default="Annually", max_length=50)),
                ("year", models.CharField(default="2025", max_length=20)),
                ("state_ut", models.CharField(db_index=True, max_length=100)),
                ("sector", models.CharField(default="Rural", max_length=50)),
                ("activity_category", models.CharField(db_index=True, max_length=150)),
                ("establishment_type", models.CharField(max_length=150)),
                ("establishments_count", models.FloatField(default=0.0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DatasetLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("village_code", models.BigIntegerField(db_index=True, unique=True)),
                ("state", models.CharField(db_index=True, max_length=100)),
                ("district", models.CharField(db_index=True, max_length=100)),
                (
                    "taluka_sub_district",
                    models.CharField(db_index=True, max_length=100),
                ),
                ("village", models.CharField(db_index=True, max_length=150)),
                (
                    "area_locality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("district_code", models.IntegerField(blank=True, null=True)),
                ("state_code", models.IntegerField(blank=True, null=True)),
                ("latitude", models.FloatField(db_index=True)),
                ("longitude", models.FloatField(db_index=True)),
                ("population", models.IntegerField(default=1500)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DatasetRouting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("village_code", models.BigIntegerField(db_index=True, unique=True)),
                ("village_name", models.CharField(max_length=150)),
                ("straight_line_distance_km", models.FloatField(default=0.0)),
                ("road_distance_km", models.FloatField(default=0.0)),
                ("travel_time_minutes", models.IntegerField(default=0)),
                ("nearest_highway_distance_km", models.FloatField(default=0.0)),
                ("nearest_mandi_distance_km", models.FloatField(default=0.0)),
                ("nearest_railway_station_km", models.FloatField(default=0.0)),
                (
                    "accessibility_rating",
                    models.CharField(default="Medium", max_length=50),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EconomicIndexRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sector", models.CharField(default="Rural", max_length=50)),
                ("year", models.IntegerField(default=2025)),
                ("month", models.CharField(max_length=20)),
                ("state", models.CharField(db_index=True, max_length=100)),
                ("cpi_index", models.FloatField(default=100.0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroundwaterRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state_ut", models.CharField(db_index=True, max_length=100)),
                ("district", models.CharField(db_index=True, max_length=100)),
                ("block", models.CharField(blank=True, max_length=100, null=True)),
                ("village", models.CharField(blank=True, max_length=150, null=True)),
                ("latitude", models.FloatField(db_index=True)),
                ("longitude", models.FloatField(db_index=True)),
                (
                    "date_recorded",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "dtwl_meters",
                    models.FloatField(help_text="Depth to Water Level in meters"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InfrastructureCoopRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.CharField(max_length=20)),
                ("state_ut", models.CharField(db_index=True, max_length=100)),
                ("number_of_societies", models.IntegerField(default=0)),
                ("membership_thousands", models.FloatField(default=0.0)),
                ("share_capital", models.FloatField(default=0.0)),
                ("working_capital", models.FloatField(default=0.0)),
                ("loans_issued", models.FloatField(default=0.0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MicroEnterpriseSkillRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state_ut", models.CharField(db_index=True, max_length=100)),
                ("candidates_trained", models.IntegerField(default=0)),
                ("candidates_placed", models.IntegerField(default=0)),
                ("beneficiaries_assisted", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RuralWageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.CharField(max_length=20)),
                ("month", models.CharField(max_length=20)),
                ("state", models.CharField(db_index=True, max_length=100)),
                ("occupation", models.CharField(db_index=True, max_length=100)),
                ("item", models.CharField(max_length=150)),
                ("wage_men", models.FloatField(blank=True, null=True)),
                ("wage_women", models.FloatField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WholesaleArrivalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("market_name", models.CharField(db_index=True, max_length=150)),
                ("commodity", models.CharField(default="Chow Chow", max_length=100)),
                ("state", models.CharField(default="Telangana", max_length=100)),
                ("arrival_current_mt", models.FloatField(default=0.0)),
                ("arrival_prev_week_mt", models.FloatField(default=0.0)),
                ("arrival_prev_month_mt", models.FloatField(default=0.0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
