# Generated by Django 5.2.17 on 2026-09-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0003_asuseenterpriserecord_datasetlocation_datasetrouting_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groundwaterrecord",
            name="latitude",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="groundwaterrecord",
            name="longitude",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
